# Generated by Django 2.1.3 on 2019-06-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=30, verbose_name='項目')),
                ('category', models.IntegerField(default=0, verbose_name='支出金額')),
                ('time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
